name: CD - Deploy to Server

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@v1.0.3
      env:
        CR_PAT: ${{ secrets.Token }}
        USERNAME: vornadrkk  
        IMAGE_NAME: ghcr.io/vornadrkk/catty-reminders-app:lab2 
        SSHPASS: 123
      with:
        host: course.prafdin.ru
        port: 2424
        username: vboxuser
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: CR_PAT,USERNAME,IMAGE_NAME,SSHPASS
        script: |
          echo "$SSHPASS" | sudo -S systemctl stop catty-reminders.service || true
          echo "$SSHPASS" | sudo -S systemctl disable catty-reminders.service || true

          echo "$SSHPASS" | sudo -S bash -c "echo $CR_PAT | docker login ghcr.io -u $USERNAME --password-stdin"
          echo "$SSHPASS" | sudo -S docker pull $IMAGE_NAME
          echo "$SSHPASS" | sudo -S docker stop myapp || true
          echo "$SSHPASS" | sudo -S docker rm myapp || true
          echo "$SSHPASS" | sudo -S docker run -d \
            --name myapp \
            --restart unless-stopped \
            -p 8181:8181 \
            $IMAGE_NAME
